# Generated by Django 6.0.3 on 2026-04-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
